### ISSUE TITLE
补充一些镜像

### ISSUE THREAD

**Issue by skys215** [eryajf/Thanks-Mirror#14]
我之前还申请过一个域名guoneiyuan.com指向我收集的国内镜像、代理、CDN呢。
网站其实跳转到石墨文档：https://shimo.im/sheets/83H98wpYQJPDP3px/MODOC/ 
看看有哪些源是还没收集的就可以收集进去。

另外，建议资源对列表进行排序，方便查找（虽然ctrl+f也能搜）。

**Comment by eryajf** [comment]
感谢补充与建议，如果方便，你可以整理一下补充上来，走个PR？

另外你说排序是指按首字母排序吗，还是什么样的？

**Comment by skys215** [comment]
对，按字母排序
