### ISSUE TITLE
博客：https://wiki.eryajf.net/，Github：https://github.com/eryajf/eryajf.github.io，部分页面访问超时504 Gateway Time-out

### ISSUE THREAD

**Issue by HenryChow505** [eryajf/Thanks-Mirror#779]
由于在 https://github.com/eryajf/eryajf.github.io 仓库无法 Issues ，只能在这里反馈！！！

**Comment by HenryChow505** [comment]
截图如下：

![image](https://github.com/user-attachments/assets/f12facd9-bffa-4182-86c8-33aef3275652)

**Comment by eryajf** [comment]
感谢反馈，现在再重新尝试呢，有可能是刚刚在发布，所以有一些影响。我这会儿访问没问题呢
