### ISSUE TITLE
几个大学的镜像站又都恢复正常了

### ISSUE THREAD

**Issue by orency** [eryajf/Thanks-Mirror#79]
之前关闭的几个大学的镜像站又都恢复正常了.比如南京,南京邮电,东北,西北农林,北京交通等.应该是前端时间他们统一接到某个安全指令后,图省事直接把外网访问关闭了.实际并没有闭站.

**Comment by eryajf** [comment]
感谢提醒，前几天扫描异常的时候，我大概猜到了，所以前几天有异常的几个都没有处理，现在果然如此，稍后我会把原来的恢复一下

**Comment by orency** [comment]
> 感谢提醒，前几天扫描异常的时候，我大概猜到了，所以前几天有异常的几个都没有处理，现在果然如此，稍后我会把原来的恢复一下
看了下某几个大学镜像站的公告,好像这些大学的镜像站都会规律性的在一年的某些关键时间点同时找些措辞借口,
"服务暂不可用","例行网络维护","系统升级",
然而感觉更像是被迫断网.🙈🙉🙊
因为前段时间同时"被故障"的不止这些镜像站,还有某些大学提供的诸如测速等很多小服务
就像教育网被拔了网线😂
