### ISSUE TITLE
FreeBSD 的源需要进行修正

### ISSUE THREAD

**Issue by ykla** [eryajf/Thanks-Mirror#80]
供您参考：

FreeBSD 有四类软件源，pkg、ports、portsnap 以及 freebsd-update，均在下文列出：

 - <https://book.bsdcn.org/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-er-jie-freebsd-huan-yuan-fang-shi.html#freebsd-cn-2>

 - <https://github.com/FreeBSD-Ask/FreeBSD-Ask/edit/main/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-er-jie-freebsd-huan-yuan-fang-shi.md>

现在列出的 [Aliyun](https://developer.aliyun.com/mirror/freebsd) 、Tencent、 HUAWEI 、 兰州大学、 首都在线均 **不** 包含上述四类软件源，只有一些系统的发布镜像。此外北京交通大学开源镜像站已经不可用，请求移除。同时还请移除华为云镜像站，其很久不对 FreeBSD 进行同步了。

感谢。

**Comment by eryajf** [comment]
你应该是FreeBSD这方面的行家，方便的话，可以提交一个PR来修正补充这方面的不足，我是纯门外人，因此很多错漏。
