### ISSUE TITLE
对于某些私有镜像是否构成滥用？

### ISSUE THREAD

**Issue by frankli0324** [eryajf/Thanks-Mirror#88]
如仅为浙大校友提供服务的g.luciaz.me，以及部分教育网镜像
另，对于软件包镜像而言，教育网镜像多数可在https://mirrorz.org / https://mirrors.cernet.edu.cn/ 查询同步状态。
见https://github.com/mirrorz-org/mirrorz

**Comment by eryajf** [comment]
> 如仅为浙大校友提供服务的g.luciaz.me，以及部分教育网镜像

这块儿的确有些不妥，晚上下班之后，我会针对这些镜像做一下处理。


> 见[mirrorz-org/mirrorz](https://github.com/mirrorz-org/mirrorz)

同时把这个添加到项目中作为友链跳转。
